<a href="https://colab.research.google.com/github/Wangari-Kariuki/Data-Science-Portfolio/blob/main/Copy_of_Mini_project_4_report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Part 1: Accessing data from the NASA near Earth Asteroid API


https://colab.research.google.com/drive/1piLSs47OYqmRMNuc7hyrzNYrnLcw6v-3?usp=sharing#scrollTo=d4e5f6a7

Task1: getting a list of asteroids who had a close access to earth for the  week starting with your your next upcoming birthday (i.e., I would do May 17-23, 2026). To do this, you'll use the Neo - Feed endpoint.

In [ ]:
import requests
import pandas as pd

In [ ]:
#API_KEY = "YOUR_API_KEY_HERE"
API_KEY = "NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh"

In [ ]:
#we use request. het method to obtain data from the neo-feed endpoint
# Use requests.get to obtain data form our desired enpoint
url  = ("https://api.nasa.gov/neo/rest/v1/feed?start_date=2026-10-20&end_date=2026-10-27&api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh")
response = requests.get(url)
data = response.json()
data

{'links': {'next': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2026-10-27&end_date=2026-11-03&detailed=false&api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh',
  'previous': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2026-10-13&end_date=2026-10-20&detailed=false&api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh',
  'self': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2026-10-20&end_date=2026-10-27&detailed=false&api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
 'element_count': 119,
 'near_earth_objects': {'2026-10-27': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2152637?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '2152637',
    'neo_reference_id': '2152637',
    'name': '152637 (1997 NC1)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2152637',
    'absolute_magnitude_h': 17.87,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.708851033,
      'estimated_diameter_max': 1.5850390958},
     'meters': {'estimated_diameter_min': 708.8510330298,
      'estimated_diameter_max': 1585.0390957756},
     'miles': {'estimated_diameter_min': 0.4404594752,
      'estimated_diameter_max': 0.984897328},
     'feet': {'estimated_diameter_min': 2325.6268232055,
      'estimated_diameter_max': 5200.2596669844}},
    'is_potentially_hazardous_asteroid': True,
    'close_approach_data': [{'close_approach_date': '2026-10-27',
      'close_approach_date_full': '2026-Oct-27 13:34',
      'epoch_date_close_approach': 1793108040000,
      'relative_velocity': {'kilometers_per_second': '9.0233656655',
       'kilometers_per_hour': '32484.1163957116',
       'miles_per_hour': '20184.366657102'},
      'miss_distance': {'astronomical': '0.3030644891',
       'lunar': '117.8920862599',
       'kilometers': '45337802.041998217',
       'miles': '28171603.8542687146'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2398188?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '2398188',
    'neo_reference_id': '2398188',
    'name': '398188 Agni (2010 LE15)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2398188',
    'absolute_magnitude_h': 19.33,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.3618719966,
      'estimated_diameter_max': 0.8091703835},
     'meters': {'estimated_diameter_min': 361.8719965994,
      'estimated_diameter_max': 809.1703835499},
     'miles': {'estimated_diameter_min': 0.2248567644,
      'estimated_diameter_max': 0.5027950104},
     'feet': {'estimated_diameter_min': 1187.2441213233,
      'estimated_diameter_max': 2654.758561166}},
    'is_potentially_hazardous_asteroid': True,
    'close_approach_data': [{'close_approach_date': '2026-10-27',
      'close_approach_date_full': '2026-Oct-27 13:23',
      'epoch_date_close_approach': 1793107380000,
      'relative_velocity': {'kilometers_per_second': '6.6642898176',
       'kilometers_per_hour': '23991.443343401',
       'miles_per_hour': '14907.3498930149'},
      'miss_distance': {'astronomical': '0.3370642879',
       'lunar': '131.1180079931',
       'kilometers': '50424099.522906773',
       'miles': '31332082.5555605474'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3485264?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '3485264',
    'neo_reference_id': '3485264',
    'name': '(2010 AL30)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3485264',
    'absolute_magnitude_h': 27.2,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0096506147,
      'estimated_diameter_max': 0.0215794305},
     'meters': {'estimated_diameter_min': 9.6506146958,
      'estimated_diameter_max': 21.5794304844},
     'miles': {'estimated_diameter_min': 0.0059966121,
      'estimated_diameter_max': 0.0134088323},
     'feet': {'estimated_diameter_min': 31.6621227185,
      'estimated_diameter_max': 70.7986587106}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-27',
      'close_approach_date_full': '2026-Oct-27 17:32',
      'epoch_date_close_approach': 1793122320000,
      'relative_velocity': {'kilometers_per_second': '8.7472278996',
       'kilometers_per_hour': '31490.0204385197',
       'miles_per_hour': '19566.6740885902'},
      'miss_distance': {'astronomical': '0.3803624789',
       'lunar': '147.9610042921',
       'kilometers': '56901416.671359943',
       'miles': '35356900.7983074934'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3576729?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '3576729',
    'neo_reference_id': '3576729',
    'name': '(2011 OB57)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3576729',
    'absolute_magnitude_h': 26.0,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0167708462,
      'estimated_diameter_max': 0.0375007522},
     'meters': {'estimated_diameter_min': 16.7708462163,
      'estimated_diameter_max': 37.5007521798},
     'miles': {'estimated_diameter_min': 0.0104209175,
      'estimated_diameter_max': 0.0233018799},
     'feet': {'estimated_diameter_min': 55.0224631002,
      'estimated_diameter_max': 123.0339677816}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-27',
      'close_approach_date_full': '2026-Oct-27 16:02',
      'epoch_date_close_approach': 1793116920000,
      'relative_velocity': {'kilometers_per_second': '18.1461987738',
       'kilometers_per_hour': '65326.3155857282',
       'miles_per_hour': '40591.2320371432'},
      'miss_distance': {'astronomical': '0.3769380496',
       'lunar': '146.6289012944',
       'kilometers': '56389129.342114352',
       'miles': '35038580.2126359776'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3788075?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '3788075',
    'neo_reference_id': '3788075',
    'name': '(2017 UP6)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3788075',
    'absolute_magnitude_h': 26.1,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0160160338,
      'estimated_diameter_max': 0.0358129403},
     'meters': {'estimated_diameter_min': 16.0160337979,
      'estimated_diameter_max': 35.8129403019},
     'miles': {'estimated_diameter_min': 0.0099518989,
      'estimated_diameter_max': 0.0222531225},
     'feet': {'estimated_diameter_min': 52.5460443254,
      'estimated_diameter_max': 117.4965270602}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-27',
      'close_approach_date_full': '2026-Oct-27 02:12',
      'epoch_date_close_approach': 1793067120000,
      'relative_velocity': {'kilometers_per_second': '19.8939536094',
       'kilometers_per_hour': '71618.2329938515',
       'miles_per_hour': '44500.784828874'},
      'miss_distance': {'astronomical': '0.2442476153',
       'lunar': '95.0123223517',
       'kilometers': '36538923.001459411',
       'miles': '22704233.9437894318'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3836049?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '3836049',
    'neo_reference_id': '3836049',
    'name': '(2018 VX1)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3836049',
    'absolute_magnitude_h': 27.5,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.008405334,
      'estimated_diameter_max': 0.0187948982},
     'meters': {'estimated_diameter_min': 8.4053340207,
      'estimated_diameter_max': 18.7948982439},
     'miles': {'estimated_diameter_min': 0.0052228308,
      'estimated_diameter_max': 0.0116786047},
     'feet': {'estimated_diameter_min': 27.5765560686,
      'estimated_diameter_max': 61.6630539546}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-27',
      'close_approach_date_full': '2026-Oct-27 21:17',
      'epoch_date_close_approach': 1793135820000,
      'relative_velocity': {'kilometers_per_second': '8.7359048983',
       'kilometers_per_hour': '31449.2576339107',
       'miles_per_hour': '19541.3456670264'},
      'miss_distance': {'astronomical': '0.0923688128',
       'lunar': '35.9314681792',
       'kilometers': '13818177.649308736',
       'miles': '8586217.4430871168'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3879723?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '3879723',
    'neo_reference_id': '3879723',
    'name': '(2019 UQ6)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3879723',
    'absolute_magnitude_h': 25.72,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0190789723,
      'estimated_diameter_max': 0.0426618789},
     'meters': {'estimated_diameter_min': 19.078972262,
      'estimated_diameter_max': 42.6618789186},
     'miles': {'estimated_diameter_min': 0.0118551201,
      'estimated_diameter_max': 0.0265088544},
     'feet': {'estimated_diameter_min': 62.595055356,
      'estimated_diameter_max': 139.9667988315}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-27',
      'close_approach_date_full': '2026-Oct-27 23:43',
      'epoch_date_close_approach': 1793144580000,
      'relative_velocity': {'kilometers_per_second': '19.8268805434',
       'kilometers_per_hour': '71376.7699563847',
       'miles_per_hour': '44350.7490876214'},
      'miss_distance': {'astronomical': '0.2916011707',
       'lunar': '113.4328554023',
       'kilometers': '43622914.026226409',
       'miles': '27106021.8529620842'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/54328015?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '54328015',
    'neo_reference_id': '54328015',
    'name': '(2022 WQ3)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=54328015',
    'absolute_magnitude_h': 28.11,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0063468024,
      'estimated_diameter_max': 0.0141918816},
     'meters': {'estimated_diameter_min': 6.34680239,
      'estimated_diameter_max': 14.1918815838},
     'miles': {'estimated_diameter_min': 0.0039437189,
      'estimated_diameter_max': 0.0088184237},
     'feet': {'estimated_diameter_min': 20.8228431532,
      'estimated_diameter_max': 46.5612927753}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-27',
      'close_approach_date_full': '2026-Oct-27 04:41',
      'epoch_date_close_approach': 1793076060000,
      'relative_velocity': {'kilometers_per_second': '25.0519742112',
       'kilometers_per_hour': '90187.1071604942',
       'miles_per_hour': '56038.7611131415'},
      'miss_distance': {'astronomical': '0.4511541608',
       'lunar': '175.4989685512',
       'kilometers': '67491701.497317496',
       'miles': '41937398.6474176048'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/54387140?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '54387140',
    'neo_reference_id': '54387140',
    'name': '(2023 SL5)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=54387140',
    'absolute_magnitude_h': 28.79,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0046403953,
      'estimated_diameter_max': 0.0103762393},
     'meters': {'estimated_diameter_min': 4.6403952825,
      'estimated_diameter_max': 10.3762392941},
     'miles': {'estimated_diameter_min': 0.0028834071,
      'estimated_diameter_max': 0.0064474942},
     'feet': {'estimated_diameter_min': 15.2243944585,
      'estimated_diameter_max': 34.0427809255}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-27',
      'close_approach_date_full': '2026-Oct-27 16:06',
      'epoch_date_close_approach': 1793117160000,
      'relative_velocity': {'kilometers_per_second': '10.243691916',
       'kilometers_per_hour': '36877.2908974934',
       'miles_per_hour': '22914.1144468342'},
      'miss_distance': {'astronomical': '0.3631405814',
       'lunar': '141.2616861646',
       'kilometers': '54325057.488001618',
       'miles': '33756025.4353456084'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': True,
    'sentry_data': 'http://api.nasa.gov/neo/rest/v1/neo/sentry/54387140?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/54445920?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '54445920',
    'neo_reference_id': '54445920',
    'name': '(2024 LJ1)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=54445920',
    'absolute_magnitude_h': 25.7,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0192555078,
      'estimated_diameter_max': 0.0430566244},
     'meters': {'estimated_diameter_min': 19.2555078188,
      'estimated_diameter_max': 43.0566244241},
     'miles': {'estimated_diameter_min': 0.0119648141,
      'estimated_diameter_max': 0.0267541378},
     'feet': {'estimated_diameter_min': 63.1742402722,
      'estimated_diameter_max': 141.2618956756}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-27',
      'close_approach_date_full': '2026-Oct-27 03:28',
      'epoch_date_close_approach': 1793071680000,
      'relative_velocity': {'kilometers_per_second': '11.0170626708',
       'kilometers_per_hour': '39661.4256150445',
       'miles_per_hour': '24644.0674884147'},
      'miss_distance': {'astronomical': '0.1569898909',
       'lunar': '61.0690675601',
       'kilometers': '23485353.290172383',
       'miles': '14593121.8424615654'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/54554261?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '54554261',
    'neo_reference_id': '54554261',
    'name': '(2025 UB5)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=54554261',
    'absolute_magnitude_h': 21.78,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1170994827,
      'estimated_diameter_max': 0.2618424035},
     'meters': {'estimated_diameter_min': 117.09948272,
      'estimated_diameter_max': 261.8424034921},
     'miles': {'estimated_diameter_min': 0.0727622227,
      'estimated_diameter_max': 0.1627012761},
     'feet': {'estimated_diameter_min': 384.1846668872,
      'estimated_diameter_max': 859.0630310729}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-27',
      'close_approach_date_full': '2026-Oct-27 09:33',
      'epoch_date_close_approach': 1793093580000,
      'relative_velocity': {'kilometers_per_second': '12.7385138501',
       'kilometers_per_hour': '45858.6498603409',
       'miles_per_hour': '28494.7816312768'},
      'miss_distance': {'astronomical': '0.1910596425',
       'lunar': '74.3222009325',
       'kilometers': '28582115.560961475',
       'miles': '17760103.062659355'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False}],
  '2026-10-22': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3615557?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '3615557',
    'neo_reference_id': '3615557',
    'name': '(2012 UA174)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3615557',
    'absolute_magnitude_h': 22.9,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0699125232,
      'estimated_diameter_max': 0.1563291544},
     'meters': {'estimated_diameter_min': 69.9125232246,
      'estimated_diameter_max': 156.3291544087},
     'miles': {'estimated_diameter_min': 0.0434416145,
      'estimated_diameter_max': 0.097138403},
     'feet': {'estimated_diameter_min': 229.3718026961,
      'estimated_diameter_max': 512.8909429502}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-22',
      'close_approach_date_full': '2026-Oct-22 11:35',
      'epoch_date_close_approach': 1792668900000,
      'relative_velocity': {'kilometers_per_second': '11.2194288313',
       'kilometers_per_hour': '40389.9437925454',
       'miles_per_hour': '25096.7403526513'},
      'miss_distance': {'astronomical': '0.3585384164',
       'lunar': '139.4714439796',
       'kilometers': '53636583.406613068',
       'miles': '33328227.4784256184'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3683469?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '3683469',
    'neo_reference_id': '3683469',
    'name': '(2014 QS295)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3683469',
    'absolute_magnitude_h': 22.05,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1034081995,
      'estimated_diameter_max': 0.2312277636},
     'meters': {'estimated_diameter_min': 103.4081995395,
      'estimated_diameter_max': 231.2277636011},
     'miles': {'estimated_diameter_min': 0.0642548564,
      'estimated_diameter_max': 0.1436782267},
     'feet': {'estimated_diameter_min': 339.2657573771,
      'estimated_diameter_max': 758.6212959332}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-22',
      'close_approach_date_full': '2026-Oct-22 06:06',
      'epoch_date_close_approach': 1792649160000,
      'relative_velocity': {'kilometers_per_second': '9.5476157769',
       'kilometers_per_hour': '34371.4167969573',
       'miles_per_hour': '21357.0617314205'},
      'miss_distance': {'astronomical': '0.3132983432',
       'lunar': '121.8730555048',
       'kilometers': '46868764.817248984',
       'miles': '29122900.0106206192'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3732669?api_key=NKsLkCUWtoL2qAI4ONS59qFsomlwCCRwCArzaTnh'},
    'id': '3732669',
    'neo_reference_id': '3732669',
    'name': '(2015 UH52)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3732669',
    'absolute_magnitude_h': 26.02,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0166170902,
      'estimated_diameter_max': 0.0371569432},
     'meters': {'estimated_diameter_min': 16.617090174,
      'estimated_diameter_max': 37.1569432173},
     'miles': {'estimated_diameter_min': 0.0103253779,
      'estimated_diameter_max': 0.023088247},
     'feet': {'estimated_diameter_min': 54.5180141264,
      'estimated_diameter_max': 121.9059855849}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2026-10-22',
      'close_approach_date_full': '2026-Oct-22 16:45',
      'epoch_date_close_approach': 1792687500000,
      'relative_velocity': {'kilometers_per_second': '15.4959422132',
       'kilometers_per_hour': '55785.3919675794',
       'miles_per_hour': '34662.873136744'},
      'miss_distance': {'astronomical': '0.1378512383',
       'lunar': '53.6241316987',

In [ ]:
data.keys()

dict_keys(['links', 'element_count', 'near_earth_objects'])

Task 2
Write code to print out, for that week, each asteroid's name along with the day of its closest approach to Earth in the following format:

In [ ]:
#we crreate an empty list
all_asteroids = []
#we loop through the dictionary, and use the .items() function to extract the values of each date key
#For context, the data is a list of lists, so near earth object key contains a list of dates
# each date is a key  for another list of asteroids
for days, asteroid_list in data['near_earth_objects'].items():
  for asteroids in asteroid_list:
    all_asteroids.append(asteroids)
  for dates in asteroids:
    adf = pd.DataFrame(all_asteroids)
adf.shape
adf.head(1)

,links,id,neo_reference_id,name,nasa_jpl_url,absolute_magnitude_h,estimated_diameter,is_potentially_hazardous_asteroid,close_approach_data,is_sentry_object,sentry_data
0,{'self': 'http://api.nasa.gov/neo/rest/v1/neo/...,2152637,2152637,152637 (1997 NC1),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,17.87,{'kilometers': {'estimated_diameter_min': 0.70...,True,"[{'close_approach_date': '2026-10-27', 'close_...",False,NaN

In [ ]:
print(type(adf['close_approach_data'][0]))
#each elemengt inside the column is a list

<class 'list'>

In [ ]:
#we loop through each list in the column, and select only the close approach date item
dates = []
for row in adf['close_approach_data']:
  if len(row) > 0:
#set the loop to append the item close approach date from each list-row
    dates.append(row[0]['close_approach_date'])
  else:
    dates.append(None)
#created a new column and stored the populated list of dates
adf['approach_dates'] = dates
adf['approach_dates']

0      2026-10-27
1      2026-10-27
2      2026-10-27
3      2026-10-27
4      2026-10-27
          ...
114    2026-10-23
115    2026-10-23
116    2026-10-23
117    2026-10-23
118    2026-10-23
Name: approach_dates, Length: 119, dtype: object

In [ ]:
adf.columns

Index(['links', 'id', 'neo_reference_id', 'name', 'nasa_jpl_url',
       'absolute_magnitude_h', 'estimated_diameter',
       'is_potentially_hazardous_asteroid', 'close_approach_data',
       'is_sentry_object', 'sentry_data', 'approach_date', 'approach_dates'],
      dtype='object')

In [ ]:
adf_copy = adf
adf_copy

,links,id,neo_reference_id,name,nasa_jpl_url,absolute_magnitude_h,estimated_diameter,is_potentially_hazardous_asteroid,close_approach_data,is_sentry_object,sentry_data,approach_date,approach_dates
0,{'self': 'http://api.nasa.gov/neo/rest/v1/neo/...,2152637,2152637,152637 (1997 NC1),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,17.87,{'kilometers': {'estimated_diameter_min': 0.70...,True,"[{'close_approach_date': '2026-10-27', 'close_...",False,NaN,2026-10-27,2026-10-27
1,{'self': 'http://api.nasa.gov/neo/rest/v1/neo/...,2398188,2398188,398188 Agni (2010 LE15),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,19.33,{'kilometers': {'estimated_diameter_min': 0.36...,True,"[{'close_approach_date': '2026-10-27', 'close_...",False,NaN,2026-10-27,2026-10-27
2,{'self': 'http://api.nasa.gov/neo/rest/v1/neo/...,3485264,3485264,(2010 AL30),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,27.20,{'kilometers': {'estimated_diameter_min': 0.00...,False,"[{'close_approach_date': '2026-10-27', 'close_...",False,NaN,2026-10-27,2026-10-27
3,{'self': 'http://api.nasa.gov/neo/rest/v1/neo/...,3576729,3576729,(2011 OB57),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,26.00,{'kilometers': {'estimated_diameter_min': 0.01...,False,"[{'close_approach_date': '2026-10-27', 'close_...",False,NaN,2026-10-27,2026-10-27
4,{'self': 'http://api.nasa.gov/neo/rest/v1/neo/...,3788075,3788075,(2017 UP6),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,26.10,{'kilometers': {'estimated_diameter_min': 0.01...,False,"[{'close_approach_date': '2026-10-27', 'close_...",False,NaN,2026-10-27,2026-10-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,{'self': 'http://api.nasa.gov/neo/rest/v1/neo/...,54131345,54131345,(2021 EL3),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,28.81,{'kilometers': {'estimated_diameter_min': 0.00...,False,"[{'close_approach_date': '2026-10-23', 'close_...",True,http://api.nasa.gov/neo/rest/v1/neo/sentry/541...,2026-10-23,2026-10-23
115,{'self': 'http://api.nasa.gov/neo/rest/v1/neo/...,54137448,54137448,(2021 GJ10),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,22.05,{'kilometers': {'estimated_diameter_min': 0.10...,False,"[{'close_approach_date': '2026-10-23', 'close_...",False,NaN,2026-10-23,2026-10-23
116,{'self': 'http://api.nasa.gov/neo/rest/v1/neo/...,54316892,54316892,(2022 UZ),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,23.84,{'kilometers': {'estimated_diameter_min': 0.04...,False,"[{'close_approach_date': '2026-10-23', 'close_...",False,NaN,2026-10-23,2026-10-23
117,{'self': 'http://api.nasa.gov/neo/rest/v1/neo/...,54351257,54351257,(2023 FU2),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,25.06,{'kilometers': {'estimated_diameter_min': 0.02...,False,"[{'close_approach_date': '2026-10-23', 'close_...",False,NaN,2026-10-23,2026-10-23
118,{'self': 'http://api.nasa.gov/neo/rest/v1/neo/...,54490521,54490521,(2024 TP11),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,25.27,{'kilometers': {'estimated_diameter_min': 0.02...,False,"[{'close_approach_date': '2026-10-23', 'close_...",False,NaN,2026-10-23,2026-10-23

In [ ]:
new_adf = adf[['name', 'approach_dates', 'id']]

In [ ]:
#extracted the diameters using a similar algorithm as the I used to extract the date
print(type(adf['estimated_diameter'][0]))

<class 'dict'>

In [ ]:
data['near_earth_objects']['2026-10-26'][0]['estimated_diameter']['meters']['estimated_diameter_max']

779.9019007224

In [ ]:
adf['estimated_diameter'][0]

{'kilometers': {'estimated_diameter_min': 0.708851033,
  'estimated_diameter_max': 1.5850390958},
 'meters': {'estimated_diameter_min': 708.8510330298,
  'estimated_diameter_max': 1585.0390957756},
 'miles': {'estimated_diameter_min': 0.4404594752,
  'estimated_diameter_max': 0.984897328},
 'feet': {'estimated_diameter_min': 2325.6268232055,
  'estimated_diameter_max': 5200.2596669844}}

In [ ]:
d = []
for index,  diameter_dict in adf['estimated_diameter'].items():
  max_diameter = diameter_dict['meters']['estimated_diameter_max']
  d.append(max_diameter)
d
new_adf['max_diameter'] = d
new_adf

/tmp/ipykernel_4051/3619459938.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_adf['max_diameter'] = d

                        name approach_dates        id  max_diameter
0          152637 (1997 NC1)     2026-10-27   2152637   1585.039096
1    398188 Agni (2010 LE15)     2026-10-27   2398188    809.170384
2                (2010 AL30)     2026-10-27   3485264     21.579430
3                (2011 OB57)     2026-10-27   3576729     37.500752
4                 (2017 UP6)     2026-10-27   3788075     35.812940
..                       ...            ...       ...           ...
114               (2021 EL3)     2026-10-23  54131345     10.281109
115              (2021 GJ10)     2026-10-23  54137448    231.227764
116                (2022 UZ)     2026-10-23  54316892    101.400473
117               (2023 FU2)     2026-10-23  54351257     57.814927
118              (2024 TP11)     2026-10-23  54490521     52.485577

[119 rows x 4 columns]

**A** The name, ID, and diameter (in meters) of the biggest asteroid in the close-approach list for your next birthday week.

In [ ]:
biggest_asteroid = new_adf.loc[new_adf['max_diameter'].idxmax()]

In [ ]:
biggest_asteroid

name              152637 (1997 NC1)
approach_dates           2026-10-27
id                          2152637
max_diameter            1585.039096
Name: 0, dtype: object

**B** The name, ID, and closest approach distance (in km) of the asteroid that will come the closest to Earth during your next birthday week.

In [ ]:
distance_in_km = []
for index_dict in adf['close_approach_data']:
  # Check if the list is not empty before trying to access its elements
  if len(index_dict) > 0:
    #miss_dist is a dictionary
    dist = index_dict[0]['miss_distance']['kilometers']
    distance_in_km.append(dist)
  else:
    distance_in_km.append(None) # Append None or handle cases where close_approach_data is empty

In [ ]:
new_adf['distance_in_km'] = distance_in_km
closest = new_adf.loc[new_adf['distance_in_km'].idxmin()]
farthest = new_adf.loc[new_adf['distance_in_km'].idxmax()]
print("closest asteroid to earth: \n ", closest )
print("farthest asteroid to earth: \n ", farthest )

closest asteroid to earth:
  name                     (2017 UQ7)
approach_dates           2026-10-25
id                          3788088
max_diameter               52.97122
distance_in_km    10212926.30821252
Name: 79, dtype: object
farthest asteroid to earth:
  name                    (2022 UP20)
approach_dates           2026-10-24
id                         54322245
max_diameter              50.820622
distance_in_km    9192321.797673694
Name: 100, dtype: object

/tmp/ipykernel_4051/626967618.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_adf['distance_in_km'] = distance_in_km

In [ ]:
new_adf['distance_in_km'].min()

'10212926.30821252'